apiVersion: apps/v1
kind: Deployment
metadata:
  name: hodor-auth
  labels:
    name: hodor-auth
    tier: back-end
spec:
  selector:
    matchLabels:
      app: hodor-auth
  replicas: 1
  template:
    metadata:
      name: back-end
      labels:
        app: hodor-auth
    spec:
      containers:
        - name: hodor-backend
          image: hodor:latest
          imagePullPolicy: IfNotPresent
