version: '3.1'

services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=hodor_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=hodor_db
    volumes:
      - db:/bitnami/postgresql
  doc: 
    image: redocly/redoc
    ports:
    - 8080:80
    environment:
    - SPEC_URL=http://localhost:3333/api-json
volumes:
  db:
